version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8010:8010"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app

  frontend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8001:8001"
    command: python -m http.server 8001